import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface DocumentReportData {
  document_name: string;
  category: string;
  responsible_person: string;
  expiry_date: string;
  status: string;
  institutes?: { name: string } | null;
}

export function generateQuarterlyPdfReport(
  instituteName: string,
  documents: DocumentReportData[],
  userName: string
) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const primaryColor: [number, number, number] = [6, 78, 59]; // #064E3B Dark Emerald
  const accentColor: [number, number, number] = [16, 185, 129]; // #10B981 Emerald
  const textColor: [number, number, number] = [30, 41, 59]; // #1E293B Slate

  // 1. Header Banner
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 38, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("ANJUMAN-I-ISLAM COMPLIANCE PORTAL", 14, 16);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("OFFICIAL QUARTERLY COMPLIANCE & AUDIT REPORT", 14, 25);

  doc.setFontSize(9);
  doc.text(`Generated on: ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`, 14, 32);

  // 2. Institution Details Box
  doc.setTextColor(...textColor);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(`Institution: ${instituteName}`, 14, 48);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated By: ${userName}`, 14, 54);

  // 3. Metric Calculations
  const total = documents.length;
  const valid = documents.filter((d) => d.status === "Valid").length;
  const expiring = documents.filter((d) => d.status === "Expiring Soon" || d.status === "Near Expiration").length;
  const expired = documents.filter((d) => d.status === "Expired").length;
  const complianceScore = total > 0 ? Math.round((valid / total) * 100) : 0;

  // Summary Metrics Table
  autoTable(doc, {
    startY: 60,
    head: [["Metric Parameter", "Count / Value", "Compliance Target"]],
    body: [
      ["Total Tracked Documents", `${total}`, "100% Repository"],
      ["Valid & Active Certificates", `${valid}`, "Target: High"],
      ["Expiring Soon (Under 90 Days)", `${expiring}`, "Requires Action"],
      ["Expired Certificates", `${expired}`, "Critical Action Required"],
      ["Overall Institute Compliance Score", `${complianceScore}%`, "Target >= 85%"],
    ],
    theme: "grid",
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
    },
  });

  // 4. Detailed Document Inventory Table
  const finalY = (doc as any).lastAutoTable.finalY || 100;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Document Inventory & Expiry Schedule", 14, finalY + 10);

  const tableRows = documents.map((d, index) => [
    index + 1,
    d.document_name,
    d.category,
    d.responsible_person || "N/A",
    d.expiry_date ? new Date(d.expiry_date).toLocaleDateString("en-IN") : "N/A",
    d.status,
  ]);

  autoTable(doc, {
    startY: finalY + 14,
    head: [["#", "Document Name", "Category", "Officer", "Expiry Date", "Status"]],
    body: tableRows,
    theme: "striped",
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    styles: {
      fontSize: 8.5,
      cellPadding: 3,
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 60 },
      2: { cellWidth: 40 },
      3: { cellWidth: 30 },
      4: { cellWidth: 25 },
      5: { cellWidth: 25 },
    },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 5) {
        const val = data.cell.raw;
        if (val === "Valid") {
          data.cell.styles.textColor = [16, 185, 129];
          data.cell.styles.fontStyle = "bold";
        } else if (val === "Expiring Soon" || val === "Near Expiration") {
          data.cell.styles.textColor = [217, 119, 6];
          data.cell.styles.fontStyle = "bold";
        } else if (val === "Expired") {
          data.cell.styles.textColor = [220, 38, 38];
          data.cell.styles.fontStyle = "bold";
        }
      }
    },
  });

  // 5. Footer Sign-off
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Anjuman-I-Islam Compliance Portal | Confidential Audit Report | Page ${i} of ${pageCount}`,
      105,
      290,
      { align: "center" }
    );
  }

  // Save File
  const safeInstName = instituteName.replace(/[^a-zA-Z0-9_]/g, "_");
  doc.save(`Quarterly_Compliance_Report_${safeInstName}.pdf`);
}
